### ISSUE TITLE
Any plans to make this work with Nextcloud?

### ISSUE THREAD

**Issue by Hund** [schiessle/shareLinkCreator#16]
Is there any plans to make this work with Nextcloud? :)

**Comment by schiessle** [comment]
Good point. Should actually work out of the box with Nextcloud, but I will have a look

**Comment by Hund** [comment]
It doesn't, I tried. It complains about bad password or username. 

I tried to solve it myself, by my knowledge about programing is slim to none. :/

**Comment by schiessle** [comment]
I can't reproduce the "bad password or username" error. Are you sure that you use that you have configured the correct username and password in the `config` file?

I could only see a failing "CSRF check" when the link gets created, this should be fixed with this commit: https://github.com/schiessle/shareLinkCreator/commit/df8b771d87b68ff34f9273bd955337fa7d9ead65

**Comment by Hund** [comment]
I'm such a derp.. I checked my config several times and I never noticed the dash instead of a dot in my url. :/ It works now. Thanks!
