### ISSUE TITLE
create share link to files already uploaded

### ISSUE THREAD

**Issue by mouseb** [schiessle/shareLinkCreator#24]
mayb it just requires a different script entirely, but 99 times out of 100, the file i would like to create a link to and share from my file manager (thunar) is already synced to nextcloud. i have no need to upload it to a links folder, but just to create a link to the file's existing path on the server. i wonder if this functionality could be achieved by editing this script?

**Comment by mouseb** [comment]
or also if the script could check if file was already uploaded before uploading...

**Comment by schiessle** [comment]
yes, that's out of scope for the script. There is no real way to check if the file already exists somewhere in your Nextcloud. The Nextcloud sync client provides some Nautilus/Dolphin integration to share files directly from within your sync folder. Maybe it wouldn't be that hard to write a similar plugin for Thunar but I never looked into it because this script was good enough for me and meanwhile I use Nautilus.
